/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example securePassword123 */
                        password: string;
                        /** @example John Doe */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                user?: components["schemas"]["User"];
                                accessToken?: string;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example securePassword123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        /** @description HTTP-only refresh token cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                user?: components["schemas"]["User"];
                                accessToken?: string;
                            };
                        };
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example Logged out successfully */
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using refresh token cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                accessToken?: string;
                            };
                        };
                    };
                };
                /** @description Invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Reset email sent (if email exists) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-reset-token/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify a password reset token is valid */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token is valid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token is invalid or expired */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using reset token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Password reset successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid token or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify email address using verification token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Email verified successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or expired token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/send-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend email verification link */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Verification email sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                user?: components["schemas"]["User"];
                            };
                        };
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        currentPassword: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Password changed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized or incorrect current password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all active sessions for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of active sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Revoke all other sessions except current */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All other sessions revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a specific session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description User role in the system
         * @enum {string}
         */
        UserRole: "USER" | "ADMIN" | "SUPER_ADMIN";
        /**
         * @description Contact message status
         * @enum {string}
         */
        ContactMessageStatus: "PENDING" | "READ" | "REPLIED";
        /**
         * @description Notification type
         * @enum {string}
         */
        NotificationType: "INFO" | "SUCCESS" | "WARNING" | "ERROR" | "SYSTEM";
        /**
         * @description Announcement type
         * @enum {string}
         */
        AnnouncementType: "INFO" | "WARNING" | "SUCCESS" | "PROMO";
        /**
         * @description Coupon discount type
         * @enum {string}
         */
        DiscountType: "PERCENTAGE" | "FIXED";
        /**
         * @description Order status
         * @enum {string}
         */
        OrderStatus: "PENDING" | "COMPLETED" | "REFUNDED" | "FAILED";
        /**
         * @description Payment method
         * @enum {string}
         */
        PaymentMethod: "STRIPE" | "PAYPAL" | "MANUAL";
        /**
         * @description Audit log action type
         * @enum {string}
         */
        AuditAction: "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "LOGIN_FAILED" | "PASSWORD_CHANGE" | "PASSWORD_RESET" | "EMAIL_VERIFY" | "ADMIN_ACTION";
        /**
         * @description Setting value type
         * @enum {string}
         */
        SettingType: "STRING" | "NUMBER" | "BOOLEAN" | "JSON";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name?: string | null;
            role: components["schemas"]["UserRole"];
            emailVerified?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name?: string | null;
            role: components["schemas"]["UserRole"];
            isActive: boolean;
            emailVerified: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Session: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            visibleId?: string;
            deviceName?: string | null;
            browser?: string | null;
            os?: string | null;
            ipAddress?: string | null;
            /** Format: date-time */
            lastActiveAt?: string;
            /** Format: date-time */
            createdAt?: string;
            isCurrent?: boolean;
        };
        ContactMessage: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            subject: string;
            message: string;
            status: components["schemas"]["ContactMessageStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            type: components["schemas"]["NotificationType"];
            title: string;
            message: string;
            data?: Record<string, never> | null;
            read: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        FaqCategory: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            order?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Faq: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId?: string | null;
            question: string;
            answer: string;
            order?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            category?: components["schemas"]["FaqCategory"];
        };
        Announcement: {
            /** Format: uuid */
            id: string;
            title: string;
            content: string;
            type: components["schemas"]["AnnouncementType"];
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            isActive?: boolean;
            isPinned?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ContentPage: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            content: string;
            metaTitle?: string | null;
            metaDesc?: string | null;
            isPublished?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Setting: {
            /** Format: uuid */
            id: string;
            key: string;
            value: string;
            type: components["schemas"]["SettingType"];
            description?: string | null;
            isPublic?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Coupon: {
            /** Format: uuid */
            id: string;
            code: string;
            discountType: components["schemas"]["DiscountType"];
            discountValue: number;
            minPurchase?: number | null;
            maxUses?: number | null;
            usedCount?: number;
            /** Format: date-time */
            validFrom?: string | null;
            /** Format: date-time */
            validUntil?: string | null;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OrderItem: {
            productId: string;
            productName: string;
            price: number;
            quantity: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            orderNumber?: string;
            /** Format: uuid */
            userId?: string | null;
            /** Format: email */
            email: string;
            status: components["schemas"]["OrderStatus"];
            paymentMethod: components["schemas"]["PaymentMethod"];
            paymentId?: string | null;
            subtotal: number;
            discount?: number;
            total: number;
            couponCode?: string | null;
            items: components["schemas"]["OrderItem"][];
            metadata?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            user?: components["schemas"]["User"];
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId?: string | null;
            action: components["schemas"]["AuditAction"];
            entity: string;
            entityId?: string | null;
            changes?: Record<string, never> | null;
            ipAddress?: string | null;
            userAgent?: string | null;
            metadata?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            user?: components["schemas"]["User"];
        };
        PaginationInfo: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
        Error: {
            /** @example false */
            success: boolean;
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example Invalid input data */
                message: string;
                details?: Record<string, never> | null;
            };
        };
        SuccessResponse: {
            /** @example true */
            success: boolean;
            message?: string;
        };
        AuthResponse: {
            success: boolean;
            data: {
                user: components["schemas"]["User"];
                accessToken: string;
                refreshToken: string;
            };
        };
        AdminStats: {
            totalUsers?: number;
            activeUsers?: number;
            totalOrders?: number;
            totalRevenue?: number;
            pendingOrders?: number;
            avgOrderValue?: number;
            recentSignups?: number;
            signupsByDay?: {
                date?: string;
                count?: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
