/**
 * Component Registry - Metadata catalog for all UI components
 * This provides structured information about each component for the showcase.
 */

import type { IconName } from "@/components/ui";

export type ComponentCategory =
  | "atoms"
  | "molecules"
  | "organisms"
  | "layouts";

export type ComponentTier = "basic" | "starter" | "pro" | "business" | "enterprise";

export interface ComponentProp {
  name: string;
  type: string;
  required: boolean;
  default?: string;
  description: string;
}

export interface ComponentMetadata {
  slug: string;
  name: string;
  description: string;
  category: ComponentCategory;
  tier: ComponentTier;
  iconName?: IconName;
  tags: string[];
  props: ComponentProp[];
  relatedComponents: string[];
  isNew?: boolean;
  isPopular?: boolean;
}

/**
 * Complete registry of all 112+ UI components
 */
export const componentRegistry: ComponentMetadata[] = [
  // =============================================================================
  // ATOMS
  // =============================================================================
  {
    slug: "button",
    name: "Button",
    description: "Primary action element with multiple variants, sizes, and states.",
    category: "atoms",
    tier: "basic",
    iconName: "MousePointer",
    tags: ["action", "form", "interactive"],
    isPopular: true,
    props: [
      { name: "variant", type: '"primary" | "secondary" | "outline" | "ghost" | "destructive" | "link"', required: false, default: '"primary"', description: "Visual style variant" },
      { name: "size", type: '"xs" | "sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Button size" },
      { name: "disabled", type: "boolean", required: false, default: "false", description: "Disable button interactions" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Show loading spinner" },
      { name: "asChild", type: "boolean", required: false, default: "false", description: "Render as child element (Slot)" },
    ],
    relatedComponents: ["icon-button", "confirm-button", "export-button"],
  },
  {
    slug: "input",
    name: "Input",
    description: "Text input field with built-in validation states and icons.",
    category: "atoms",
    tier: "basic",
    iconName: "TextCursor",
    tags: ["form", "text", "input"],
    props: [
      { name: "type", type: '"text" | "email" | "password" | "number" | ...', required: false, default: '"text"', description: "Input type" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Input size" },
      { name: "error", type: "boolean", required: false, default: "false", description: "Show error state" },
      { name: "leftIcon", type: "ReactNode", required: false, description: "Icon on the left" },
      { name: "rightIcon", type: "ReactNode", required: false, description: "Icon on the right" },
    ],
    relatedComponents: ["textarea", "search-input", "number-input", "field-wrapper"],
  },
  {
    slug: "textarea",
    name: "Textarea",
    description: "Multi-line text input with auto-resize support.",
    category: "atoms",
    tier: "basic",
    iconName: "TextAlignJustify",
    tags: ["form", "text", "multiline"],
    props: [
      { name: "rows", type: "number", required: false, default: "3", description: "Number of visible rows" },
      { name: "resize", type: '"none" | "vertical" | "horizontal" | "both"', required: false, default: '"vertical"', description: "Resize behavior" },
      { name: "error", type: "boolean", required: false, default: "false", description: "Show error state" },
    ],
    relatedComponents: ["input", "rich-text-editor", "field-wrapper"],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    description: "Boolean toggle with label and description support.",
    category: "atoms",
    tier: "basic",
    iconName: "SquareCheck",
    tags: ["form", "toggle", "boolean"],
    props: [
      { name: "checked", type: "boolean", required: false, description: "Controlled checked state" },
      { name: "defaultChecked", type: "boolean", required: false, description: "Default checked state" },
      { name: "label", type: "string", required: false, description: "Label text" },
      { name: "description", type: "string", required: false, description: "Help text" },
      { name: "indeterminate", type: "boolean", required: false, default: "false", description: "Indeterminate state" },
    ],
    relatedComponents: ["switch", "radio"],
  },
  {
    slug: "radio",
    name: "Radio",
    description: "Single selection from a group of options.",
    category: "atoms",
    tier: "basic",
    iconName: "Circle",
    tags: ["form", "selection", "options"],
    props: [
      { name: "value", type: "string", required: true, description: "Radio value" },
      { name: "name", type: "string", required: true, description: "Group name" },
      { name: "label", type: "string", required: false, description: "Label text" },
      { name: "checked", type: "boolean", required: false, description: "Controlled checked state" },
    ],
    relatedComponents: ["radio-group", "checkbox", "select"],
  },
  {
    slug: "radio-group",
    name: "RadioGroup",
    description: "Group container for radio buttons with controlled state.",
    category: "atoms",
    tier: "basic",
    iconName: "CircleDot",
    tags: ["form", "selection", "group"],
    props: [
      { name: "name", type: "string", required: true, description: "Group name for all radios" },
      { name: "value", type: "string", required: false, description: "Controlled selected value" },
      { name: "defaultValue", type: "string", required: false, description: "Default selected value" },
      { name: "options", type: "RadioOption[]", required: true, description: "Array of radio options" },
      { name: "onChange", type: "(value: string) => void", required: false, description: "Selection change handler" },
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, default: '"vertical"', description: "Layout direction" },
    ],
    relatedComponents: ["radio", "checkbox", "select"],
  },
  {
    slug: "select",
    name: "Select",
    description: "Dropdown selection with search and multi-select support.",
    category: "atoms",
    tier: "basic",
    iconName: "ChevronDown",
    tags: ["form", "dropdown", "selection"],
    isPopular: true,
    props: [
      { name: "options", type: "SelectOption[]", required: true, description: "Array of options" },
      { name: "value", type: "string | string[]", required: false, description: "Selected value(s)" },
      { name: "placeholder", type: "string", required: false, default: '"Select..."', description: "Placeholder text" },
      { name: "multiple", type: "boolean", required: false, default: "false", description: "Allow multiple selection" },
      { name: "searchable", type: "boolean", required: false, default: "false", description: "Enable search filter" },
    ],
    relatedComponents: ["autocomplete", "radio-group", "dropdown-menu"],
  },
  {
    slug: "switch",
    name: "Switch",
    description: "Toggle switch for on/off settings.",
    category: "atoms",
    tier: "basic",
    iconName: "ToggleRight",
    tags: ["form", "toggle", "boolean"],
    props: [
      { name: "checked", type: "boolean", required: false, description: "Controlled checked state" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Switch size" },
      { name: "label", type: "string", required: false, description: "Label text" },
    ],
    relatedComponents: ["checkbox", "radio"],
  },
  {
    slug: "slider",
    name: "Slider",
    description: "Range slider input with marks and tooltip.",
    category: "atoms",
    tier: "basic",
    iconName: "SlidersHorizontal",
    tags: ["form", "range", "number"],
    props: [
      { name: "value", type: "number | number[]", required: false, description: "Current value(s)" },
      { name: "min", type: "number", required: false, default: "0", description: "Minimum value" },
      { name: "max", type: "number", required: false, default: "100", description: "Maximum value" },
      { name: "step", type: "number", required: false, default: "1", description: "Step increment" },
      { name: "marks", type: "SliderMark[]", required: false, description: "Tick marks" },
    ],
    relatedComponents: ["number-input", "progress"],
  },
  {
    slug: "rating",
    name: "Rating",
    description: "Star rating input and display.",
    category: "atoms",
    tier: "basic",
    iconName: "Star",
    tags: ["form", "rating", "stars"],
    props: [
      { name: "value", type: "number", required: false, default: "0", description: "Current rating" },
      { name: "max", type: "number", required: false, default: "5", description: "Maximum stars" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Star size" },
      { name: "readonly", type: "boolean", required: false, default: "false", description: "Read-only mode" },
      { name: "allowHalf", type: "boolean", required: false, default: "false", description: "Allow half stars" },
    ],
    relatedComponents: ["slider"],
  },
  {
    slug: "number-input",
    name: "NumberInput",
    description: "Numeric input with increment/decrement buttons.",
    category: "atoms",
    tier: "basic",
    iconName: "Hash",
    tags: ["form", "number", "input"],
    props: [
      { name: "value", type: "number", required: false, description: "Current value" },
      { name: "min", type: "number", required: false, description: "Minimum value" },
      { name: "max", type: "number", required: false, description: "Maximum value" },
      { name: "step", type: "number", required: false, default: "1", description: "Step increment" },
      { name: "precision", type: "number", required: false, description: "Decimal places" },
    ],
    relatedComponents: ["input", "slider"],
  },
  {
    slug: "badge",
    name: "Badge",
    description: "Status and label indicator with variants.",
    category: "atoms",
    tier: "basic",
    iconName: "Tag",
    tags: ["display", "status", "label"],
    isPopular: true,
    props: [
      { name: "variant", type: '"default" | "secondary" | "outline" | "destructive" | "success" | "warning"', required: false, default: '"default"', description: "Visual variant" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Badge size" },
      { name: "dot", type: "boolean", required: false, default: "false", description: "Show status dot" },
    ],
    relatedComponents: ["status-badge"],
  },
  {
    slug: "spinner",
    name: "Spinner",
    description: "Loading indicator with overlay support.",
    category: "atoms",
    tier: "basic",
    iconName: "Loader",
    tags: ["loading", "feedback", "status"],
    props: [
      { name: "size", type: '"xs" | "sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Spinner size" },
      { name: "color", type: '"primary" | "secondary" | "white"', required: false, default: '"primary"', description: "Spinner color" },
    ],
    relatedComponents: ["skeleton", "progress", "spinner-overlay"],
  },
  {
    slug: "spinner-overlay",
    name: "SpinnerOverlay",
    description: "Full-screen or container overlay with centered spinner.",
    category: "atoms",
    tier: "basic",
    iconName: "Loader",
    tags: ["loading", "overlay", "blocking"],
    props: [
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Spinner size" },
      { name: "label", type: "string", required: false, description: "Loading text below spinner" },
      { name: "blur", type: "boolean", required: false, default: "false", description: "Blur background content" },
      { name: "fullScreen", type: "boolean", required: false, default: "false", description: "Cover entire viewport" },
    ],
    relatedComponents: ["spinner"],
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    description: "Loading placeholder with various presets.",
    category: "atoms",
    tier: "basic",
    iconName: "Square",
    tags: ["loading", "placeholder"],
    props: [
      { name: "width", type: "string | number", required: false, description: "Skeleton width" },
      { name: "height", type: "string | number", required: false, description: "Skeleton height" },
      { name: "rounded", type: "boolean", required: false, default: "false", description: "Rounded corners" },
      { name: "animate", type: "boolean", required: false, default: "true", description: "Pulse animation" },
    ],
    relatedComponents: ["spinner", "skeleton-text", "skeleton-circle", "skeleton-card", "skeleton-table", "skeleton-avatar"],
  },
  {
    slug: "skeleton-text",
    name: "SkeletonText",
    description: "Text line placeholder for loading states.",
    category: "atoms",
    tier: "basic",
    iconName: "Type",
    tags: ["loading", "placeholder", "text"],
    props: [
      { name: "lines", type: "number", required: false, default: "3", description: "Number of text lines" },
      { name: "spacing", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Line spacing" },
      { name: "lastLineWidth", type: "string", required: false, default: '"60%"', description: "Last line width" },
    ],
    relatedComponents: ["skeleton"],
  },
  {
    slug: "skeleton-circle",
    name: "SkeletonCircle",
    description: "Circular skeleton for avatars and icons.",
    category: "atoms",
    tier: "basic",
    iconName: "Circle",
    tags: ["loading", "placeholder", "avatar"],
    props: [
      { name: "size", type: "string | number", required: false, default: "40", description: "Circle diameter" },
    ],
    relatedComponents: ["skeleton", "skeleton-avatar"],
  },
  {
    slug: "skeleton-card",
    name: "SkeletonCard",
    description: "Card-shaped loading placeholder.",
    category: "atoms",
    tier: "basic",
    iconName: "SquareDashed",
    tags: ["loading", "placeholder", "card"],
    props: [
      { name: "showImage", type: "boolean", required: false, default: "true", description: "Show image placeholder" },
      { name: "showTitle", type: "boolean", required: false, default: "true", description: "Show title placeholder" },
      { name: "lines", type: "number", required: false, default: "2", description: "Description lines" },
    ],
    relatedComponents: ["skeleton", "card"],
  },
  {
    slug: "skeleton-avatar",
    name: "SkeletonAvatar",
    description: "Avatar placeholder with optional text lines.",
    category: "atoms",
    tier: "basic",
    iconName: "CircleUser",
    tags: ["loading", "placeholder", "avatar"],
    props: [
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Avatar size" },
      { name: "showText", type: "boolean", required: false, default: "true", description: "Show name placeholder" },
    ],
    relatedComponents: ["skeleton", "avatar"],
  },
  {
    slug: "skeleton-button",
    name: "SkeletonButton",
    description: "Button placeholder for loading states.",
    category: "atoms",
    tier: "basic",
    iconName: "RectangleHorizontal",
    tags: ["loading", "placeholder", "button"],
    props: [
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Button size" },
      { name: "width", type: "string | number", required: false, description: "Custom width" },
    ],
    relatedComponents: ["skeleton", "button"],
  },
  {
    slug: "skeleton-image",
    name: "SkeletonImage",
    description: "Image placeholder with aspect ratio.",
    category: "atoms",
    tier: "basic",
    iconName: "Image",
    tags: ["loading", "placeholder", "image"],
    props: [
      { name: "aspectRatio", type: "number", required: false, default: "1.5", description: "Width/height ratio" },
      { name: "width", type: "string | number", required: false, default: '"100%"', description: "Image width" },
    ],
    relatedComponents: ["skeleton"],
  },
  {
    slug: "skeleton-table",
    name: "SkeletonTable",
    description: "Table placeholder for loading data.",
    category: "atoms",
    tier: "basic",
    iconName: "Table",
    tags: ["loading", "placeholder", "table"],
    props: [
      { name: "rows", type: "number", required: false, default: "5", description: "Number of rows" },
      { name: "columns", type: "number", required: false, default: "4", description: "Number of columns" },
      { name: "showHeader", type: "boolean", required: false, default: "true", description: "Show header row" },
    ],
    relatedComponents: ["skeleton", "table", "data-table"],
  },
  {
    slug: "skeleton-list",
    name: "SkeletonList",
    description: "List placeholder for loading items.",
    category: "atoms",
    tier: "basic",
    iconName: "List",
    tags: ["loading", "placeholder", "list"],
    props: [
      { name: "items", type: "number", required: false, default: "5", description: "Number of items" },
      { name: "showAvatar", type: "boolean", required: false, default: "false", description: "Show avatar per item" },
      { name: "showSecondary", type: "boolean", required: false, default: "true", description: "Show secondary text" },
    ],
    relatedComponents: ["skeleton"],
  },
  {
    slug: "skeleton-page",
    name: "SkeletonPage",
    description: "Full page loading placeholder.",
    category: "atoms",
    tier: "basic",
    iconName: "FileText",
    tags: ["loading", "placeholder", "page"],
    props: [
      { name: "showHeader", type: "boolean", required: false, default: "true", description: "Show header section" },
      { name: "showSidebar", type: "boolean", required: false, default: "false", description: "Show sidebar" },
    ],
    relatedComponents: ["skeleton", "page-layout"],
  },
  {
    slug: "skeleton-dashboard",
    name: "SkeletonDashboard",
    description: "Dashboard loading placeholder with stats and charts.",
    category: "atoms",
    tier: "basic",
    iconName: "LayoutDashboard",
    tags: ["loading", "placeholder", "dashboard"],
    props: [
      { name: "statCards", type: "number", required: false, default: "4", description: "Number of stat cards" },
      { name: "showChart", type: "boolean", required: false, default: "true", description: "Show chart placeholder" },
      { name: "showTable", type: "boolean", required: false, default: "true", description: "Show table placeholder" },
    ],
    relatedComponents: ["skeleton", "dashboard-layout", "stat-card"],
  },
  {
    slug: "skeleton-form",
    name: "SkeletonForm",
    description: "Form loading placeholder with fields.",
    category: "atoms",
    tier: "basic",
    iconName: "TextCursorInput",
    tags: ["loading", "placeholder", "form"],
    props: [
      { name: "fields", type: "number", required: false, default: "4", description: "Number of fields" },
      { name: "showLabels", type: "boolean", required: false, default: "true", description: "Show field labels" },
      { name: "showButton", type: "boolean", required: false, default: "true", description: "Show submit button" },
    ],
    relatedComponents: ["skeleton", "field-wrapper"],
  },
  {
    slug: "skeleton-profile",
    name: "SkeletonProfile",
    description: "User profile loading placeholder.",
    category: "atoms",
    tier: "basic",
    iconName: "User",
    tags: ["loading", "placeholder", "profile"],
    props: [
      { name: "showCover", type: "boolean", required: false, default: "true", description: "Show cover image" },
      { name: "showStats", type: "boolean", required: false, default: "true", description: "Show user stats" },
    ],
    relatedComponents: ["skeleton", "avatar"],
  },
  {
    slug: "skeleton-auth",
    name: "SkeletonAuth",
    description: "Authentication form loading placeholder.",
    category: "atoms",
    tier: "basic",
    iconName: "Lock",
    tags: ["loading", "placeholder", "auth"],
    props: [
      { name: "showLogo", type: "boolean", required: false, default: "true", description: "Show logo placeholder" },
      { name: "showSocial", type: "boolean", required: false, default: "true", description: "Show social buttons" },
    ],
    relatedComponents: ["skeleton", "auth-layout"],
  },
  {
    slug: "progress",
    name: "Progress",
    description: "Linear and circular progress indicators.",
    category: "atoms",
    tier: "basic",
    iconName: "ChartBar",
    tags: ["loading", "progress", "status"],
    props: [
      { name: "value", type: "number", required: false, default: "0", description: "Progress value (0-100)" },
      { name: "variant", type: '"linear" | "circular"', required: false, default: '"linear"', description: "Progress type" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Progress size" },
      { name: "color", type: '"primary" | "success" | "warning" | "destructive"', required: false, default: '"primary"', description: "Progress color" },
      { name: "showValue", type: "boolean", required: false, default: "false", description: "Show percentage" },
    ],
    relatedComponents: ["spinner", "slider", "linear-progress", "circular-progress"],
  },
  {
    slug: "linear-progress",
    name: "LinearProgress",
    description: "Horizontal progress bar with animation.",
    category: "atoms",
    tier: "basic",
    iconName: "Minus",
    tags: ["loading", "progress", "bar"],
    props: [
      { name: "value", type: "number", required: false, default: "0", description: "Progress value (0-100)" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Bar height" },
      { name: "color", type: '"primary" | "success" | "warning" | "destructive"', required: false, default: '"primary"', description: "Bar color" },
      { name: "indeterminate", type: "boolean", required: false, default: "false", description: "Indeterminate animation" },
      { name: "striped", type: "boolean", required: false, default: "false", description: "Striped pattern" },
    ],
    relatedComponents: ["progress", "circular-progress"],
  },
  {
    slug: "circular-progress",
    name: "CircularProgress",
    description: "Circular progress ring with percentage.",
    category: "atoms",
    tier: "basic",
    iconName: "CircleDashed",
    tags: ["loading", "progress", "circle"],
    props: [
      { name: "value", type: "number", required: false, default: "0", description: "Progress value (0-100)" },
      { name: "size", type: '"sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Ring size" },
      { name: "color", type: '"primary" | "success" | "warning" | "destructive"', required: false, default: '"primary"', description: "Ring color" },
      { name: "thickness", type: "number", required: false, default: "4", description: "Stroke width" },
      { name: "showValue", type: "boolean", required: false, default: "true", description: "Show center percentage" },
    ],
    relatedComponents: ["progress", "linear-progress"],
  },
  {
    slug: "label",
    name: "Label",
    description: "Form field label with required indicator.",
    category: "atoms",
    tier: "basic",
    iconName: "Type",
    tags: ["form", "text", "label"],
    props: [
      { name: "htmlFor", type: "string", required: false, description: "Associated input ID" },
      { name: "required", type: "boolean", required: false, default: "false", description: "Show required indicator" },
    ],
    relatedComponents: ["field-wrapper", "input"],
  },
  {
    slug: "icon",
    name: "Icon",
    description: "Lucide icon wrapper with consistent sizing.",
    category: "atoms",
    tier: "basic",
    iconName: "Sparkles",
    tags: ["display", "icon", "visual"],
    props: [
      { name: "name", type: "IconName", required: true, description: "Lucide icon name" },
      { name: "size", type: '"xs" | "sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Icon size" },
      { name: "color", type: "string", required: false, description: "Icon color" },
    ],
    relatedComponents: ["icon-button"],
  },
  {
    slug: "link",
    name: "AppLink",
    description: "Internal/external link with styling options.",
    category: "atoms",
    tier: "basic",
    iconName: "Link",
    tags: ["navigation", "link", "text"],
    props: [
      { name: "href", type: "string", required: true, description: "Link destination" },
      { name: "external", type: "boolean", required: false, default: "false", description: "Open in new tab" },
      { name: "variant", type: '"default" | "muted" | "underline"', required: false, default: '"default"', description: "Link style" },
    ],
    relatedComponents: ["nav-link", "button"],
  },
  {
    slug: "text",
    name: "Text",
    description: "Typography component with semantic variants.",
    category: "atoms",
    tier: "basic",
    iconName: "Type",
    tags: ["typography", "text", "display"],
    props: [
      { name: "variant", type: '"h1" | "h2" | "h3" | "h4" | "body" | "small" | "muted"', required: false, default: '"body"', description: "Text variant" },
      { name: "as", type: "ElementType", required: false, description: "HTML element to render" },
      { name: "color", type: '"default" | "muted" | "primary" | "destructive"', required: false, description: "Text color" },
    ],
    relatedComponents: ["label"],
  },
  {
    slug: "divider",
    name: "Divider",
    description: "Visual separator with optional label.",
    category: "atoms",
    tier: "basic",
    iconName: "Minus",
    tags: ["layout", "separator", "visual"],
    props: [
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, default: '"horizontal"', description: "Divider direction" },
      { name: "variant", type: '"solid" | "dashed" | "dotted"', required: false, default: '"solid"', description: "Line style" },
      { name: "label", type: "string", required: false, description: "Center label text" },
    ],
    relatedComponents: [],
  },
  {
    slug: "kbd",
    name: "Kbd",
    description: "Keyboard key indicator for shortcuts.",
    category: "atoms",
    tier: "basic",
    iconName: "Keyboard",
    tags: ["display", "keyboard", "shortcut"],
    props: [
      { name: "children", type: "ReactNode", required: true, description: "Key text" },
    ],
    relatedComponents: ["menu-item"],
  },
  {
    slug: "visually-hidden",
    name: "VisuallyHidden",
    description: "Screen reader only content for accessibility.",
    category: "atoms",
    tier: "basic",
    iconName: "EyeOff",
    tags: ["accessibility", "a11y", "hidden"],
    props: [
      { name: "children", type: "ReactNode", required: true, description: "Hidden content" },
    ],
    relatedComponents: [],
  },
  {
    slug: "card",
    name: "Card",
    description: "Container with border, shadow, and sections.",
    category: "atoms",
    tier: "basic",
    iconName: "Square",
    tags: ["container", "layout", "surface"],
    isPopular: true,
    props: [
      { name: "variant", type: '"default" | "outline" | "ghost" | "elevated"', required: false, default: '"default"', description: "Card style" },
      { name: "padding", type: '"none" | "sm" | "md" | "lg"', required: false, default: '"md"', description: "Inner padding" },
      { name: "hover", type: "boolean", required: false, default: "false", description: "Hover effect" },
    ],
    relatedComponents: ["card-header", "card-title", "card-description", "card-content", "card-footer", "stat-card"],
  },
  {
    slug: "card-header",
    name: "CardHeader",
    description: "Card header section with title and description slots.",
    category: "atoms",
    tier: "basic",
    iconName: "LayoutTemplate",
    tags: ["container", "layout", "header"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["card", "card-title", "card-description"],
  },
  {
    slug: "card-title",
    name: "CardTitle",
    description: "Card title text with proper heading styling.",
    category: "atoms",
    tier: "basic",
    iconName: "Heading",
    tags: ["typography", "title", "card"],
    props: [
      { name: "as", type: '"h1" | "h2" | "h3" | "h4" | "h5" | "h6"', required: false, default: '"h3"', description: "Heading element" },
    ],
    relatedComponents: ["card", "card-header"],
  },
  {
    slug: "card-description",
    name: "CardDescription",
    description: "Card description text with muted styling.",
    category: "atoms",
    tier: "basic",
    iconName: "FileText",
    tags: ["typography", "description", "card"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["card", "card-header"],
  },
  {
    slug: "card-content",
    name: "CardContent",
    description: "Card main content area with padding.",
    category: "atoms",
    tier: "basic",
    iconName: "SquareDashed",
    tags: ["container", "content", "card"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["card"],
  },
  {
    slug: "card-footer",
    name: "CardFooter",
    description: "Card footer section for actions.",
    category: "atoms",
    tier: "basic",
    iconName: "LayoutTemplate",
    tags: ["container", "footer", "card"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["card", "button"],
  },
  {
    slug: "table",
    name: "Table",
    description: "Data table with sorting and pagination support.",
    category: "atoms",
    tier: "basic",
    iconName: "Table",
    tags: ["data", "table", "display"],
    isPopular: true,
    props: [
      { name: "striped", type: "boolean", required: false, default: "false", description: "Striped rows" },
      { name: "hoverable", type: "boolean", required: false, default: "false", description: "Row hover effect" },
      { name: "compact", type: "boolean", required: false, default: "false", description: "Compact spacing" },
    ],
    relatedComponents: ["table-header", "table-body", "table-footer", "table-row", "table-head", "table-cell", "table-caption", "data-table"],
  },
  {
    slug: "table-header",
    name: "TableHeader",
    description: "Table header section containing column headers.",
    category: "atoms",
    tier: "basic",
    iconName: "Rows2",
    tags: ["data", "table", "header"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["table", "table-row", "table-head"],
  },
  {
    slug: "table-body",
    name: "TableBody",
    description: "Table body section containing data rows.",
    category: "atoms",
    tier: "basic",
    iconName: "Rows3",
    tags: ["data", "table", "body"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["table", "table-row", "table-cell"],
  },
  {
    slug: "table-footer",
    name: "TableFooter",
    description: "Table footer section for summaries.",
    category: "atoms",
    tier: "basic",
    iconName: "Rows4",
    tags: ["data", "table", "footer"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["table", "table-row"],
  },
  {
    slug: "table-row",
    name: "TableRow",
    description: "Table row container for cells.",
    category: "atoms",
    tier: "basic",
    iconName: "GripHorizontal",
    tags: ["data", "table", "row"],
    props: [
      { name: "selected", type: "boolean", required: false, default: "false", description: "Selected state" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["table", "table-head", "table-cell"],
  },
  {
    slug: "table-head",
    name: "TableHead",
    description: "Table header cell with sorting support.",
    category: "atoms",
    tier: "basic",
    iconName: "CaseSensitive",
    tags: ["data", "table", "header"],
    props: [
      { name: "sortable", type: "boolean", required: false, default: "false", description: "Enable sorting" },
      { name: "sorted", type: '"asc" | "desc" | false', required: false, description: "Sort direction" },
      { name: "onSort", type: "() => void", required: false, description: "Sort handler" },
    ],
    relatedComponents: ["table", "table-header", "table-row"],
  },
  {
    slug: "table-cell",
    name: "TableCell",
    description: "Table data cell.",
    category: "atoms",
    tier: "basic",
    iconName: "RectangleHorizontal",
    tags: ["data", "table", "cell"],
    props: [
      { name: "align", type: '"left" | "center" | "right"', required: false, default: '"left"', description: "Text alignment" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["table", "table-body", "table-row"],
  },
  {
    slug: "table-caption",
    name: "TableCaption",
    description: "Table caption for accessibility.",
    category: "atoms",
    tier: "basic",
    iconName: "Captions",
    tags: ["data", "table", "caption", "a11y"],
    props: [
      { name: "side", type: '"top" | "bottom"', required: false, default: '"bottom"', description: "Caption position" },
    ],
    relatedComponents: ["table"],
  },
  {
    slug: "data-table",
    name: "DataTable",
    description: "Reusable data table with loading and empty states.",
    category: "atoms",
    tier: "basic",
    iconName: "Table2",
    tags: ["data", "table", "display"],
    props: [
      { name: "columns", type: "Column[]", required: true, description: "Column definitions" },
      { name: "data", type: "T[]", required: true, description: "Table data" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Loading state" },
      { name: "emptyMessage", type: "string", required: false, description: "Empty state message" },
    ],
    relatedComponents: ["table", "pagination"],
  },

  // =============================================================================
  // MOLECULES
  // =============================================================================
  {
    slug: "avatar",
    name: "Avatar",
    description: "User avatar with image fallback and status indicator.",
    category: "molecules",
    tier: "basic",
    iconName: "User",
    tags: ["display", "user", "image"],
    isPopular: true,
    props: [
      { name: "src", type: "string", required: false, description: "Image source URL" },
      { name: "alt", type: "string", required: false, description: "Alt text" },
      { name: "name", type: "string", required: false, description: "Name for initials fallback" },
      { name: "size", type: '"xs" | "sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Avatar size" },
      { name: "status", type: '"online" | "offline" | "away" | "busy"', required: false, description: "Status indicator" },
    ],
    relatedComponents: ["avatar-upload"],
  },
  {
    slug: "nav-link",
    name: "NavLink",
    description: "Navigation link with active state detection.",
    category: "molecules",
    tier: "basic",
    iconName: "Navigation",
    tags: ["navigation", "link", "menu"],
    props: [
      { name: "href", type: "string", required: true, description: "Link destination" },
      { name: "icon", type: "IconName", required: false, description: "Left icon" },
      { name: "variant", type: '"default" | "sidebar" | "tab"', required: false, default: '"default"', description: "Link style" },
      { name: "exact", type: "boolean", required: false, default: "false", description: "Exact path matching" },
    ],
    relatedComponents: ["link", "breadcrumb"],
  },
  {
    slug: "icon-button",
    name: "IconButton",
    description: "Button with icon only and tooltip.",
    category: "molecules",
    tier: "basic",
    iconName: "MousePointer2",
    tags: ["action", "icon", "button"],
    props: [
      { name: "icon", type: "IconName", required: true, description: "Icon to display" },
      { name: "label", type: "string", required: true, description: "Accessible label (tooltip)" },
      { name: "variant", type: '"ghost" | "outline" | "primary"', required: false, default: '"ghost"', description: "Button variant" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Button size" },
    ],
    relatedComponents: ["button", "tooltip"],
  },
  {
    slug: "menu-item",
    name: "MenuItem",
    description: "Menu action item with icon and keyboard shortcut.",
    category: "molecules",
    tier: "basic",
    iconName: "List",
    tags: ["menu", "action", "navigation"],
    props: [
      { name: "icon", type: "IconName", required: false, description: "Left icon" },
      { name: "shortcut", type: "string", required: false, description: "Keyboard shortcut" },
      { name: "destructive", type: "boolean", required: false, default: "false", description: "Destructive style" },
      { name: "disabled", type: "boolean", required: false, default: "false", description: "Disabled state" },
    ],
    relatedComponents: ["dropdown-menu", "kbd"],
  },
  {
    slug: "field-wrapper",
    name: "FieldWrapper",
    description: "Form field container with label and error handling.",
    category: "molecules",
    tier: "basic",
    iconName: "TextCursorInput",
    tags: ["form", "wrapper", "validation"],
    props: [
      { name: "label", type: "string", required: false, description: "Field label" },
      { name: "error", type: "string", required: false, description: "Error message" },
      { name: "description", type: "string", required: false, description: "Help text" },
      { name: "required", type: "boolean", required: false, default: "false", description: "Required indicator" },
    ],
    relatedComponents: ["label", "input", "textarea"],
  },
  {
    slug: "status-badge",
    name: "StatusBadge",
    description: "Status indicator with dot and label.",
    category: "molecules",
    tier: "basic",
    iconName: "Circle",
    tags: ["status", "display", "badge"],
    props: [
      { name: "status", type: '"success" | "warning" | "error" | "info" | "pending"', required: true, description: "Status type" },
      { name: "label", type: "string", required: false, description: "Custom label text" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Badge size" },
    ],
    relatedComponents: ["badge"],
  },
  {
    slug: "theme-toggle",
    name: "ThemeToggle",
    description: "Dark/light mode switch button.",
    category: "molecules",
    tier: "basic",
    iconName: "Moon",
    tags: ["theme", "toggle", "settings"],
    props: [
      { name: "variant", type: '"icon" | "switch" | "dropdown"', required: false, default: '"icon"', description: "Toggle style" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Toggle size" },
    ],
    relatedComponents: ["theme-selector", "switch"],
  },
  {
    slug: "theme-selector",
    name: "ThemeSelector",
    description: "Theme dropdown with system/light/dark options.",
    category: "molecules",
    tier: "basic",
    iconName: "Palette",
    tags: ["theme", "settings", "dropdown"],
    props: [
      { name: "variant", type: '"minimal" | "labeled"', required: false, default: '"minimal"', description: "Display style" },
      { name: "size", type: '"sm" | "md"', required: false, default: '"md"', description: "Selector size" },
    ],
    relatedComponents: ["theme-toggle", "dropdown-menu"],
  },
  {
    slug: "password-strength",
    name: "PasswordStrengthMeter",
    description: "Password validation indicator with requirements.",
    category: "molecules",
    tier: "starter",
    iconName: "ShieldCheck",
    tags: ["form", "validation", "security"],
    props: [
      { name: "password", type: "string", required: true, description: "Password to validate" },
      { name: "minLength", type: "number", required: false, default: "8", description: "Minimum length" },
      { name: "showRequirements", type: "boolean", required: false, default: "true", description: "Show requirement list" },
    ],
    relatedComponents: ["input", "progress"],
  },
  {
    slug: "confirm-button",
    name: "ConfirmButton",
    description: "Button with built-in confirmation dialog.",
    category: "molecules",
    tier: "basic",
    iconName: "TriangleAlert",
    tags: ["action", "confirmation", "dialog"],
    props: [
      { name: "onConfirm", type: "() => void", required: true, description: "Confirm callback" },
      { name: "title", type: "string", required: false, description: "Dialog title" },
      { name: "message", type: "string", required: false, description: "Confirmation message" },
      { name: "confirmText", type: "string", required: false, default: '"Confirm"', description: "Confirm button text" },
      { name: "mode", type: '"dialog" | "popover" | "double-click"', required: false, default: '"dialog"', description: "Confirmation mode" },
    ],
    relatedComponents: ["button", "dialog"],
  },
  {
    slug: "export-button",
    name: "ExportButton",
    description: "Download/export action buttons.",
    category: "molecules",
    tier: "pro",
    iconName: "Download",
    tags: ["action", "export", "download"],
    props: [
      { name: "onExport", type: "() => void | Promise<void>", required: true, description: "Export handler" },
      { name: "filename", type: "string", required: false, description: "Download filename" },
      { name: "format", type: '"csv" | "json" | "pdf" | "xlsx"', required: false, description: "Export format" },
    ],
    relatedComponents: ["button", "export-csv-button", "export-my-data-button"],
  },
  {
    slug: "export-csv-button",
    name: "ExportCsvButton",
    description: "Export data as CSV file.",
    category: "molecules",
    tier: "pro",
    iconName: "FileSpreadsheet",
    tags: ["action", "export", "csv"],
    props: [
      { name: "data", type: "Record<string, unknown>[]", required: true, description: "Data to export" },
      { name: "filename", type: "string", required: false, default: '"export.csv"', description: "Download filename" },
      { name: "columns", type: "string[]", required: false, description: "Column headers" },
    ],
    relatedComponents: ["export-button"],
  },
  {
    slug: "export-my-data-button",
    name: "ExportMyDataButton",
    description: "GDPR-compliant personal data export button.",
    category: "molecules",
    tier: "enterprise",
    iconName: "UserCheck",
    tags: ["action", "export", "gdpr", "privacy"],
    props: [
      { name: "onExport", type: "() => Promise<Blob>", required: true, description: "Data fetch handler" },
      { name: "format", type: '"json" | "zip"', required: false, default: '"json"', description: "Export format" },
    ],
    relatedComponents: ["export-button"],
  },
  {
    slug: "autocomplete",
    name: "Autocomplete",
    description: "Search input with suggestions dropdown.",
    category: "molecules",
    tier: "basic",
    iconName: "Search",
    tags: ["form", "search", "input"],
    props: [
      { name: "options", type: "AutocompleteOption[]", required: true, description: "Suggestion options" },
      { name: "value", type: "string", required: false, description: "Selected value" },
      { name: "onSearch", type: "(query: string) => void", required: false, description: "Search callback" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Loading state" },
      { name: "freeSolo", type: "boolean", required: false, default: "false", description: "Allow custom values" },
    ],
    relatedComponents: ["search-input", "select", "command-palette"],
  },
  {
    slug: "search-input",
    name: "SearchInput",
    description: "Search input with debounce and loading state.",
    category: "molecules",
    tier: "basic",
    iconName: "Search",
    tags: ["form", "search", "input"],
    isPopular: true,
    props: [
      { name: "value", type: "string", required: false, description: "Search value" },
      { name: "onChange", type: "(value: string) => void", required: false, description: "Change handler" },
      { name: "debounce", type: "number", required: false, default: "300", description: "Debounce delay (ms)" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Loading state" },
      { name: "onClear", type: "() => void", required: false, description: "Clear callback" },
    ],
    relatedComponents: ["input", "autocomplete"],
  },
  {
    slug: "command-palette",
    name: "CommandPalette",
    description: "Command palette with fuzzy search.",
    category: "molecules",
    tier: "pro",
    iconName: "Command",
    tags: ["navigation", "search", "keyboard"],
    isNew: true,
    props: [
      { name: "commands", type: "CommandGroup[]", required: true, description: "Command groups" },
      { name: "open", type: "boolean", required: false, description: "Controlled open state" },
      { name: "onOpenChange", type: "(open: boolean) => void", required: false, description: "Open change handler" },
      { name: "placeholder", type: "string", required: false, default: '"Type a command..."', description: "Search placeholder" },
    ],
    relatedComponents: ["dialog", "search-input"],
  },
  {
    slug: "tag-input",
    name: "TagInput",
    description: "Multi-value tag input with create support.",
    category: "molecules",
    tier: "basic",
    iconName: "Tags",
    tags: ["form", "input", "multi-value"],
    props: [
      { name: "value", type: "string[]", required: false, description: "Selected tags" },
      { name: "suggestions", type: "string[]", required: false, description: "Tag suggestions" },
      { name: "maxTags", type: "number", required: false, description: "Maximum tags" },
      { name: "allowCreate", type: "boolean", required: false, default: "true", description: "Allow new tags" },
    ],
    relatedComponents: ["badge", "autocomplete"],
  },
  {
    slug: "qr-code",
    name: "QRCode",
    description: "QR code generator with download.",
    category: "molecules",
    tier: "starter",
    iconName: "QrCode",
    tags: ["display", "code", "sharing"],
    props: [
      { name: "value", type: "string", required: true, description: "QR code data" },
      { name: "size", type: "number", required: false, default: "128", description: "QR code size" },
      { name: "errorCorrection", type: '"L" | "M" | "Q" | "H"', required: false, default: '"M"', description: "Error correction level" },
      { name: "download", type: "boolean", required: false, default: "false", description: "Show download button" },
    ],
    relatedComponents: [],
  },
  {
    slug: "avatar-upload",
    name: "AvatarUpload",
    description: "Avatar with upload and crop functionality.",
    category: "molecules",
    tier: "pro",
    iconName: "ImagePlus",
    tags: ["form", "upload", "image"],
    props: [
      { name: "src", type: "string", required: false, description: "Current image" },
      { name: "onUpload", type: "(file: File) => void | Promise<void>", required: true, description: "Upload handler" },
      { name: "maxSize", type: "number", required: false, default: "5242880", description: "Max file size (bytes)" },
      { name: "accept", type: "string", required: false, default: '"image/*"', description: "Accepted file types" },
    ],
    relatedComponents: ["avatar", "image-upload"],
  },
  {
    slug: "copy-button",
    name: "CopyButton",
    description: "Copy text to clipboard with feedback.",
    category: "molecules",
    tier: "basic",
    iconName: "Copy",
    tags: ["action", "clipboard", "utility"],
    props: [
      { name: "text", type: "string", required: true, description: "Text to copy" },
      { name: "onCopy", type: "(text: string) => void", required: false, description: "Copy callback" },
      { name: "variant", type: '"icon" | "button"', required: false, default: '"icon"', description: "Display variant" },
    ],
    relatedComponents: ["copyable-text", "icon-button"],
  },
  {
    slug: "copyable-text",
    name: "CopyableText",
    description: "Text with inline copy button.",
    category: "molecules",
    tier: "basic",
    iconName: "ClipboardCopy",
    tags: ["display", "clipboard", "utility"],
    props: [
      { name: "text", type: "string", required: true, description: "Text to display and copy" },
      { name: "truncate", type: "boolean", required: false, default: "false", description: "Truncate long text" },
    ],
    relatedComponents: ["copy-button"],
  },
  {
    slug: "stat-card",
    name: "StatCard",
    description: "Statistics display card with trend indicator.",
    category: "molecules",
    tier: "pro",
    iconName: "TrendingUp",
    tags: ["display", "analytics", "dashboard"],
    isPopular: true,
    props: [
      { name: "title", type: "string", required: true, description: "Stat title" },
      { name: "value", type: "string | number", required: true, description: "Stat value" },
      { name: "change", type: "number", required: false, description: "Change percentage" },
      { name: "trend", type: '"up" | "down" | "neutral"', required: false, description: "Trend direction" },
      { name: "icon", type: "IconName", required: false, description: "Left icon" },
    ],
    relatedComponents: ["card", "stat-card-skeleton"],
  },
  {
    slug: "stat-card-skeleton",
    name: "StatCardSkeleton",
    description: "Loading placeholder for statistics cards.",
    category: "molecules",
    tier: "pro",
    iconName: "TrendingUp",
    tags: ["loading", "placeholder", "dashboard"],
    props: [
      { name: "showIcon", type: "boolean", required: false, default: "true", description: "Show icon placeholder" },
      { name: "showTrend", type: "boolean", required: false, default: "true", description: "Show trend placeholder" },
    ],
    relatedComponents: ["stat-card", "skeleton"],
  },
  {
    slug: "rich-text-editor",
    name: "RichTextEditor",
    description: "WYSIWYG editor with formatting toolbar.",
    category: "molecules",
    tier: "pro",
    iconName: "FileText",
    tags: ["form", "editor", "text"],
    props: [
      { name: "value", type: "string", required: false, description: "HTML content" },
      { name: "onChange", type: "(value: string) => void", required: false, description: "Change handler" },
      { name: "toolbar", type: "ToolbarOption[]", required: false, description: "Toolbar buttons" },
      { name: "placeholder", type: "string", required: false, description: "Placeholder text" },
    ],
    relatedComponents: ["textarea"],
  },
  {
    slug: "date-picker",
    name: "DatePicker",
    description: "Calendar dropdown for date selection.",
    category: "molecules",
    tier: "basic",
    iconName: "Calendar",
    tags: ["form", "date", "input"],
    isPopular: true,
    props: [
      { name: "value", type: "Date", required: false, description: "Selected date" },
      { name: "onChange", type: "(date: Date | null) => void", required: false, description: "Change handler" },
      { name: "minDate", type: "Date", required: false, description: "Minimum date" },
      { name: "maxDate", type: "Date", required: false, description: "Maximum date" },
      { name: "format", type: "string", required: false, default: '"PP"', description: "Date format" },
    ],
    relatedComponents: ["time-picker"],
  },
  {
    slug: "time-picker",
    name: "TimePicker",
    description: "Time selection dropdown.",
    category: "molecules",
    tier: "basic",
    iconName: "Clock",
    tags: ["form", "time", "input"],
    props: [
      { name: "value", type: "TimeValue", required: false, description: "Selected time" },
      { name: "onChange", type: "(time: TimeValue | null) => void", required: false, description: "Change handler" },
      { name: "format", type: '"12h" | "24h"', required: false, default: '"12h"', description: "Time format" },
      { name: "minuteStep", type: "number", required: false, default: "15", description: "Minute increment" },
    ],
    relatedComponents: ["date-picker"],
  },

  // =============================================================================
  // ORGANISMS
  // =============================================================================
  {
    slug: "dialog",
    name: "Dialog",
    description: "Modal dialog with header, body, and footer sections.",
    category: "organisms",
    tier: "basic",
    iconName: "Maximize2",
    tags: ["overlay", "modal", "dialog"],
    isPopular: true,
    props: [
      { name: "open", type: "boolean", required: true, description: "Open state" },
      { name: "onClose", type: "() => void", required: true, description: "Close handler" },
      { name: "size", type: '"sm" | "md" | "lg" | "xl" | "full"', required: false, default: '"md"', description: "Dialog size" },
      { name: "closeOnOverlayClick", type: "boolean", required: false, default: "true", description: "Close on backdrop click" },
    ],
    relatedComponents: ["modal", "dialog-header", "dialog-body", "dialog-footer"],
  },
  {
    slug: "dialog-header",
    name: "DialogHeader",
    description: "Dialog header with title and close button.",
    category: "organisms",
    tier: "basic",
    iconName: "LayoutTemplate",
    tags: ["overlay", "modal", "header"],
    props: [
      { name: "showCloseButton", type: "boolean", required: false, default: "true", description: "Show close button" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["dialog"],
  },
  {
    slug: "dialog-body",
    name: "DialogBody",
    description: "Dialog main content area with scrolling.",
    category: "organisms",
    tier: "basic",
    iconName: "SquareDashed",
    tags: ["overlay", "modal", "content"],
    props: [
      { name: "scrollable", type: "boolean", required: false, default: "true", description: "Enable scrolling" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["dialog"],
  },
  {
    slug: "dialog-footer",
    name: "DialogFooter",
    description: "Dialog footer with action buttons.",
    category: "organisms",
    tier: "basic",
    iconName: "LayoutTemplate",
    tags: ["overlay", "modal", "footer"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["dialog", "button"],
  },
  {
    slug: "modal",
    name: "Modal",
    description: "Simplified dialog wrapper for common modal use cases.",
    category: "organisms",
    tier: "basic",
    iconName: "LayoutTemplate",
    tags: ["overlay", "modal", "dialog"],
    props: [
      { name: "open", type: "boolean", required: true, description: "Open state" },
      { name: "onClose", type: "() => void", required: true, description: "Close handler" },
      { name: "title", type: "string", required: false, description: "Modal title" },
      { name: "description", type: "string", required: false, description: "Modal description" },
      { name: "footer", type: "ReactNode", required: false, description: "Footer content" },
    ],
    relatedComponents: ["dialog"],
  },
  {
    slug: "tabs",
    name: "Tabs",
    description: "Tabbed content navigation.",
    category: "organisms",
    tier: "basic",
    iconName: "FolderOpen",
    tags: ["navigation", "tabs", "content"],
    isPopular: true,
    props: [
      { name: "value", type: "string", required: false, description: "Controlled active tab" },
      { name: "defaultValue", type: "string", required: false, description: "Default active tab" },
      { name: "onChange", type: "(value: string) => void", required: false, description: "Tab change handler" },
      { name: "variant", type: '"default" | "pills" | "underline"', required: false, default: '"default"', description: "Tab style" },
    ],
    relatedComponents: ["tab-list", "tab", "tab-panels", "tab-panel"],
  },
  {
    slug: "tab-list",
    name: "TabList",
    description: "Container for tab triggers.",
    category: "organisms",
    tier: "basic",
    iconName: "LayoutList",
    tags: ["navigation", "tabs", "list"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["tabs", "tab"],
  },
  {
    slug: "tab",
    name: "Tab",
    description: "Individual tab trigger button.",
    category: "organisms",
    tier: "basic",
    iconName: "PanelTop",
    tags: ["navigation", "tabs", "trigger"],
    props: [
      { name: "value", type: "string", required: true, description: "Tab value identifier" },
      { name: "disabled", type: "boolean", required: false, default: "false", description: "Disabled state" },
      { name: "icon", type: "IconName", required: false, description: "Tab icon" },
    ],
    relatedComponents: ["tabs", "tab-list"],
  },
  {
    slug: "tab-panels",
    name: "TabPanels",
    description: "Container for tab content panels.",
    category: "organisms",
    tier: "basic",
    iconName: "Layers",
    tags: ["navigation", "tabs", "container"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["tabs", "tab-panel"],
  },
  {
    slug: "tab-panel",
    name: "TabPanel",
    description: "Individual tab content panel.",
    category: "organisms",
    tier: "basic",
    iconName: "PanelBottom",
    tags: ["navigation", "tabs", "content"],
    props: [
      { name: "value", type: "string", required: true, description: "Panel value (matches tab)" },
      { name: "keepMounted", type: "boolean", required: false, default: "false", description: "Keep content mounted when hidden" },
    ],
    relatedComponents: ["tabs", "tab-panels"],
  },
  {
    slug: "accordion",
    name: "Accordion",
    description: "Expandable content sections.",
    category: "organisms",
    tier: "basic",
    iconName: "ChevronDown",
    tags: ["display", "collapse", "content"],
    props: [
      { name: "type", type: '"single" | "multiple"', required: false, default: '"single"', description: "Single or multiple open" },
      { name: "collapsible", type: "boolean", required: false, default: "true", description: "Allow all closed" },
      { name: "defaultValue", type: "string | string[]", required: false, description: "Default open items" },
    ],
    relatedComponents: ["accordion-item", "accordion-trigger", "accordion-content", "collapsible"],
  },
  {
    slug: "accordion-item",
    name: "AccordionItem",
    description: "Individual accordion section container.",
    category: "organisms",
    tier: "basic",
    iconName: "SquareStack",
    tags: ["display", "collapse", "item"],
    props: [
      { name: "value", type: "string", required: true, description: "Unique item identifier" },
      { name: "disabled", type: "boolean", required: false, default: "false", description: "Disabled state" },
    ],
    relatedComponents: ["accordion", "accordion-trigger", "accordion-content"],
  },
  {
    slug: "accordion-trigger",
    name: "AccordionTrigger",
    description: "Clickable header that toggles accordion item.",
    category: "organisms",
    tier: "basic",
    iconName: "ChevronRight",
    tags: ["display", "collapse", "trigger"],
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
    relatedComponents: ["accordion", "accordion-item"],
  },
  {
    slug: "accordion-content",
    name: "AccordionContent",
    description: "Collapsible content area of accordion item.",
    category: "organisms",
    tier: "basic",
    iconName: "SquareDashed",
    tags: ["display", "collapse", "content"],
    props: [
      { name: "forceMount", type: "boolean", required: false, default: "false", description: "Force content mount" },
    ],
    relatedComponents: ["accordion", "accordion-item"],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    description: "Hover-triggered overlay with positioning.",
    category: "organisms",
    tier: "basic",
    iconName: "MessageSquare",
    tags: ["overlay", "tooltip", "help"],
    props: [
      { name: "content", type: "ReactNode", required: true, description: "Tooltip content" },
      { name: "side", type: '"top" | "right" | "bottom" | "left"', required: false, default: '"top"', description: "Tooltip position" },
      { name: "delay", type: "number", required: false, default: "200", description: "Show delay (ms)" },
      { name: "arrow", type: "boolean", required: false, default: "true", description: "Show arrow" },
    ],
    relatedComponents: ["popover"],
  },
  {
    slug: "popover",
    name: "Popover",
    description: "Click-triggered overlay with content.",
    category: "organisms",
    tier: "basic",
    iconName: "MessageCircle",
    tags: ["overlay", "popover", "content"],
    props: [
      { name: "trigger", type: "ReactNode", required: true, description: "Trigger element" },
      { name: "content", type: "ReactNode", required: true, description: "Popover content" },
      { name: "side", type: '"top" | "right" | "bottom" | "left"', required: false, default: '"bottom"', description: "Popover position" },
      { name: "align", type: '"start" | "center" | "end"', required: false, default: '"center"', description: "Alignment" },
    ],
    relatedComponents: ["tooltip", "dropdown-menu"],
  },
  {
    slug: "stepper",
    name: "Stepper",
    description: "Multi-step workflow navigation.",
    category: "organisms",
    tier: "starter",
    iconName: "ListOrdered",
    tags: ["navigation", "workflow", "steps"],
    props: [
      { name: "steps", type: "Step[]", required: true, description: "Step definitions" },
      { name: "activeStep", type: "number", required: false, default: "0", description: "Current step index" },
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, default: '"horizontal"', description: "Stepper orientation" },
      { name: "clickable", type: "boolean", required: false, default: "false", description: "Allow step clicking" },
    ],
    relatedComponents: ["step", "step-indicator", "step-label", "step-connector"],
  },
  {
    slug: "step",
    name: "Step",
    description: "Individual step in a stepper workflow.",
    category: "organisms",
    tier: "starter",
    iconName: "CircleDot",
    tags: ["navigation", "workflow", "step"],
    props: [
      { name: "index", type: "number", required: true, description: "Step index" },
      { name: "label", type: "string", required: false, description: "Step label" },
      { name: "description", type: "string", required: false, description: "Step description" },
      { name: "icon", type: "IconName", required: false, description: "Custom step icon" },
    ],
    relatedComponents: ["stepper", "step-indicator"],
  },
  {
    slug: "step-indicator",
    name: "StepIndicator",
    description: "Visual indicator for step state.",
    category: "organisms",
    tier: "starter",
    iconName: "CircleCheck",
    tags: ["navigation", "workflow", "indicator"],
    props: [
      { name: "state", type: '"pending" | "active" | "completed" | "error"', required: true, description: "Step state" },
      { name: "number", type: "number", required: false, description: "Step number" },
    ],
    relatedComponents: ["stepper", "step"],
  },
  {
    slug: "step-label",
    name: "StepLabel",
    description: "Label and description for a step.",
    category: "organisms",
    tier: "starter",
    iconName: "Tag",
    tags: ["navigation", "workflow", "label"],
    props: [
      { name: "label", type: "string", required: true, description: "Step label" },
      { name: "description", type: "string", required: false, description: "Step description" },
      { name: "optional", type: "boolean", required: false, default: "false", description: "Mark as optional" },
    ],
    relatedComponents: ["stepper", "step"],
  },
  {
    slug: "step-connector",
    name: "StepConnector",
    description: "Visual connector line between steps.",
    category: "organisms",
    tier: "starter",
    iconName: "Minus",
    tags: ["navigation", "workflow", "connector"],
    props: [
      { name: "completed", type: "boolean", required: false, default: "false", description: "Completed state" },
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, default: '"horizontal"', description: "Connector orientation" },
    ],
    relatedComponents: ["stepper"],
  },
  {
    slug: "timeline",
    name: "Timeline",
    description: "Vertical timeline display.",
    category: "organisms",
    tier: "starter",
    iconName: "GitCommitHorizontal",
    tags: ["display", "history", "timeline"],
    props: [
      { name: "items", type: "TimelineItemData[]", required: true, description: "Timeline items" },
      { name: "size", type: '"sm" | "md" | "lg"', required: false, default: '"md"', description: "Timeline size" },
      { name: "alternating", type: "boolean", required: false, default: "false", description: "Alternating sides" },
    ],
    relatedComponents: ["timeline-item"],
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    description: "Expandable/collapsible content.",
    category: "organisms",
    tier: "basic",
    iconName: "ChevronsUpDown",
    tags: ["display", "collapse", "content"],
    props: [
      { name: "open", type: "boolean", required: false, description: "Controlled open state" },
      { name: "defaultOpen", type: "boolean", required: false, default: "false", description: "Default open state" },
      { name: "onOpenChange", type: "(open: boolean) => void", required: false, description: "Open change handler" },
    ],
    relatedComponents: ["accordion", "collapsible-trigger", "collapsible-content"],
  },
  {
    slug: "dropdown-menu",
    name: "DropdownMenu",
    description: "Dropdown menu with keyboard navigation.",
    category: "organisms",
    tier: "basic",
    iconName: "EllipsisVertical",
    tags: ["menu", "dropdown", "navigation"],
    isPopular: true,
    props: [
      { name: "trigger", type: "ReactNode", required: true, description: "Trigger element" },
      { name: "items", type: "DropdownMenuContent", required: true, description: "Menu items" },
      { name: "align", type: '"start" | "center" | "end"', required: false, default: '"end"', description: "Menu alignment" },
      { name: "side", type: '"top" | "right" | "bottom" | "left"', required: false, default: '"bottom"', description: "Menu side" },
    ],
    relatedComponents: ["menu-item", "popover"],
  },
  {
    slug: "pagination",
    name: "Pagination",
    description: "Page navigation with ellipsis and size selector.",
    category: "organisms",
    tier: "basic",
    iconName: "ArrowLeftRight",
    tags: ["navigation", "pagination", "list"],
    props: [
      { name: "page", type: "number", required: true, description: "Current page (1-indexed)" },
      { name: "totalPages", type: "number", required: true, description: "Total pages" },
      { name: "onPageChange", type: "(page: number) => void", required: true, description: "Page change handler" },
      { name: "pageSize", type: "number", required: false, description: "Items per page" },
      { name: "showSizeChanger", type: "boolean", required: false, default: "false", description: "Show page size selector" },
    ],
    relatedComponents: ["data-table"],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    description: "Navigation breadcrumb with separators.",
    category: "organisms",
    tier: "basic",
    iconName: "ChevronRight",
    tags: ["navigation", "breadcrumb", "path"],
    props: [
      { name: "items", type: "BreadcrumbItem[]", required: true, description: "Breadcrumb items" },
      { name: "separator", type: "ReactNode", required: false, default: '"/"', description: "Separator element" },
      { name: "maxItems", type: "number", required: false, description: "Max visible items" },
    ],
    relatedComponents: ["nav-link"],
  },

  // =============================================================================
  // LAYOUTS
  // =============================================================================
  {
    slug: "container",
    name: "Container",
    description: "Centered content wrapper with max-width.",
    category: "layouts",
    tier: "basic",
    iconName: "LayoutDashboard",
    tags: ["layout", "container", "wrapper"],
    props: [
      { name: "size", type: '"sm" | "md" | "lg" | "xl" | "full"', required: false, default: '"lg"', description: "Maximum width" },
      { name: "padding", type: '"none" | "sm" | "md" | "lg"', required: false, default: '"md"', description: "Horizontal padding" },
      { name: "as", type: "ElementType", required: false, default: '"div"', description: "Wrapper element" },
    ],
    relatedComponents: ["stack", "grid"],
  },
  {
    slug: "stack",
    name: "Stack",
    description: "Vertical/horizontal flex container.",
    category: "layouts",
    tier: "basic",
    iconName: "LayoutList",
    tags: ["layout", "flex", "spacing"],
    props: [
      { name: "direction", type: '"row" | "column"', required: false, default: '"column"', description: "Stack direction" },
      { name: "gap", type: '"none" | "xs" | "sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Gap between items" },
      { name: "align", type: '"start" | "center" | "end" | "stretch"', required: false, description: "Cross-axis alignment" },
      { name: "justify", type: '"start" | "center" | "end" | "between" | "around"', required: false, description: "Main-axis alignment" },
    ],
    relatedComponents: ["container", "grid"],
  },
  {
    slug: "grid",
    name: "Grid",
    description: "Responsive grid layout.",
    category: "layouts",
    tier: "basic",
    iconName: "LayoutGrid",
    tags: ["layout", "grid", "responsive"],
    props: [
      { name: "cols", type: "ResponsiveValue<1-12>", required: false, default: "1", description: "Number of columns" },
      { name: "gap", type: '"none" | "xs" | "sm" | "md" | "lg" | "xl"', required: false, default: '"md"', description: "Gap between items" },
      { name: "alignItems", type: '"start" | "center" | "end" | "stretch"', required: false, description: "Cross-axis alignment" },
    ],
    relatedComponents: ["grid-item", "container", "stack"],
  },
  {
    slug: "auth-layout",
    name: "AuthLayout",
    description: "Authentication page layout with background.",
    category: "layouts",
    tier: "starter",
    iconName: "Lock",
    tags: ["layout", "auth", "page"],
    props: [
      { name: "title", type: "string", required: false, description: "Page title" },
      { name: "description", type: "string", required: false, description: "Page description" },
      { name: "maxWidth", type: '"sm" | "md" | "lg"', required: false, default: '"sm"', description: "Content max width" },
      { name: "showLogo", type: "boolean", required: false, default: "true", description: "Show logo" },
    ],
    relatedComponents: ["background-pattern"],
  },
  {
    slug: "page-layout",
    name: "PageLayout",
    description: "Standard page with optional sidebar.",
    category: "layouts",
    tier: "basic",
    iconName: "LayoutTemplate",
    tags: ["layout", "page", "sidebar"],
    props: [
      { name: "sidebar", type: "ReactNode", required: false, description: "Sidebar content" },
      { name: "sidebarPosition", type: '"left" | "right"', required: false, default: '"left"', description: "Sidebar position" },
      { name: "sidebarWidth", type: "string | number", required: false, default: "280", description: "Sidebar width" },
      { name: "collapsible", type: "boolean", required: false, default: "false", description: "Allow sidebar collapse" },
    ],
    relatedComponents: ["sidebar-toggle", "container"],
  },
  {
    slug: "dashboard-layout",
    name: "DashboardLayout",
    description: "Admin/dashboard layout with navigation.",
    category: "layouts",
    tier: "pro",
    iconName: "LayoutDashboard",
    tags: ["layout", "dashboard", "admin"],
    isPopular: true,
    props: [
      { name: "sidebar", type: "ReactNode", required: false, description: "Sidebar content" },
      { name: "header", type: "ReactNode", required: false, description: "Header content" },
      { name: "sidebarCollapsed", type: "boolean", required: false, default: "false", description: "Sidebar collapsed state" },
    ],
    relatedComponents: ["dashboard-sidebar", "dashboard-nav-item", "dashboard-header"],
  },
  {
    slug: "split-layout",
    name: "SplitLayout",
    description: "Two-panel layout with resizable split.",
    category: "layouts",
    tier: "pro",
    iconName: "Columns2",
    tags: ["layout", "split", "panels"],
    props: [
      { name: "left", type: "ReactNode", required: true, description: "Left panel content" },
      { name: "right", type: "ReactNode", required: true, description: "Right panel content" },
      { name: "ratio", type: '"30/70" | "40/60" | "50/50" | "60/40" | "70/30"', required: false, default: '"50/50"', description: "Split ratio" },
      { name: "resizable", type: "boolean", required: false, default: "false", description: "Allow resizing" },
    ],
    relatedComponents: ["resizable-split-layout"],
  },
];

/**
 * Get all unique categories
 */
export function getCategories(): ComponentCategory[] {
  return ["atoms", "molecules", "organisms", "layouts"];
}

/**
 * Get category display info
 */
export function getCategoryInfo(category: ComponentCategory) {
  const info = {
    atoms: {
      name: "Atoms",
      description: "Basic building blocks - single HTML elements with styling",
      icon: "Atom" as IconName,
    },
    molecules: {
      name: "Molecules",
      description: "Combinations of atoms forming functional units",
      icon: "Component" as IconName,
    },
    organisms: {
      name: "Organisms",
      description: "Complex UI patterns with multiple molecules",
      icon: "Boxes" as IconName,
    },
    layouts: {
      name: "Layouts",
      description: "Page structure and composition components",
      icon: "LayoutTemplate" as IconName,
    },
  };
  return info[category];
}

/**
 * Get components by category
 */
export function getComponentsByCategory(category: ComponentCategory): ComponentMetadata[] {
  return componentRegistry.filter((c) => c.category === category);
}

/**
 * Get component by slug
 */
export function getComponentBySlug(slug: string): ComponentMetadata | undefined {
  return componentRegistry.find((c) => c.slug === slug);
}

/**
 * Search components
 */
export function searchComponents(query: string): ComponentMetadata[] {
  const q = query.toLowerCase();
  return componentRegistry.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.tags.some((t) => t.toLowerCase().includes(q))
  );
}

/**
 * Get tier display info
 */
export function getTierInfo(tier: ComponentTier) {
  const info = {
    basic: { name: "Basic", color: "secondary" as const },
    starter: { name: "Starter", color: "default" as const },
    pro: { name: "Pro", color: "default" as const },
    business: { name: "Business", color: "default" as const },
    enterprise: { name: "Enterprise", color: "default" as const },
  };
  return info[tier];
}

/**
 * Get popular components
 */
export function getPopularComponents(): ComponentMetadata[] {
  return componentRegistry.filter((c) => c.isPopular);
}

/**
 * Get new components
 */
export function getNewComponents(): ComponentMetadata[] {
  return componentRegistry.filter((c) => c.isNew);
}
